### ISSUE TITLE
Cannot compile code: 'class UpdaterClass' has no member named 'run'

### ISSUE THREAD

**Issue by tommueller** [universam1/Brauhelferlein#4]
I cannot compile the project, I get the following error:

> /home/tom/Dokumente/Projekte/Brauen/Brausteuerung/Brauhelferlein/Brauhelferlein.ino: In lambda function:
> Brauhelferlein:302: error: 'class UpdaterClass' has no member named 'runAsync'
> Update.runAsync(true);
> exit status 1
> 'class UpdaterClass' has no member named 'runAsync'

Thanks
Tom

**Comment by universam1** [comment]
did you add the ESPAsync* Libraries?

**Comment by tommueller** [comment]
yes. The code is right from the project and all libs are imported

**Comment by tommueller** [comment]
Okay. I updated to the latest GIT Version of the Arduino ESP8266 Board (https://github.com/esp8266/Arduino)

Now I'm having trouble with the LiquidCrystal Library.

http://pastebin.com/4BW9NbKD

What board did you select?

**Comment by universam1** [comment]
You are using an outdated version of the LCD library, double check it!

Try https://bitbucket.org/fmalpartida/new-liquidcrystal/get/tip.zip

**Comment by tommueller** [comment]
Ok I fixed it. Apparently from the download page (https://bitbucket.org/fmalpartida/new-liquidcrystal/downloads) you have to choose **Download repository** and not the "highest version number" ...

Thanks
